firstname = input("Enter your first name: ")
print("My First Name is", firstname)
print()
color = input("Enter your favourite color: ")
print("Your favourite color is", color)
print()
Age = int(input("How old are you? :"))
print("I am", Age, "years old.")
print()
height = float(input("Enter your height: "))
print("Your height is ", height, "ft")
print()
print("Thank you!")
